---
apiVersion: v1
kind: Namespace
metadata:
  name: cherrypicker
---
apiVersion: v1
kind: Service
metadata:
  name: cherrypicker
  namespace: cherrypicker
  labels:
    app: cherrypicker
spec:
  type: LoadBalancer
  selector:
    app: cherrypicker
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherrypicker
  namespace: cherrypicker
  labels:
    app: cherrypicker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cherrypicker
  template:
    metadata:
      labels:
        app: cherrypicker
    spec:
      containers:
        - name: cherrypicker
          image: docker.io/ealebed/cherrypicker:2025.10.13-11.25
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: LISTEN_PORT
              value: ":8080"
            - name: GITHUB_APP_ID
              value: "2077471"
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: gh-webhook-secret
                  key: value
            - name: GITHUB_APP_PRIVATE_KEY_PEM_BASE64
              valueFrom:
                secretKeyRef:
                  name: gh-app-private-key-b64
                  key: value
            - name: GIT_USER_NAME
              value: "cherry-pick-bot"
            - name: GIT_USER_EMAIL
              value: "cherry-pick-bot@users.noreply.github.com"
            - name: LOG_LEVEL
              value: "info"
            - name: AWS_REGION
              value: "eu-north-1"
            - name: SQS_QUEUE_URL
              value: "https://sqs.eu-north-1.amazonaws.com/531438381462/ghapp-poc-queue"
            - name: SQS_MAX_MESSAGES
              value: "10"
            - name: SQS_WAIT_TIME_SECONDS
              value: "10"
            - name: SQS_VISIBILITY_TIMEOUT
              value: "120"
            - name: SQS_DELETE_ON_4XX
              value: "true"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
